"""
Test script for Gmail MCP tools and resources.

Tests Gmail operations in a sequential flow:
1. List messages (resource)
2. Get message details (resource)
3. Send email (tool)
4. List messages again to verify sent email
"""
import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
# test_script.py is in: covalent_mcp/toolclasses/google/mail/
# Need to go up 5 levels to get to project root
covalent_mcp_dir = Path(__file__).parent.parent.parent.parent  # Gets to covalent_mcp/
project_root = covalent_mcp_dir.parent  # Gets to project root
sys.path.insert(0, str(project_root))

from covalent_mcp.toolclasses.google.gauth import GoogleAuth, DEFAULT_SCOPES
from covalent_mcp.toolclasses.google.mail.gmail_client import GmailService


# Initialize client (shared across all tests)
auth = GoogleAuth(scopes=DEFAULT_SCOPES)
client = GmailService(auth=auth)


def test_list_messages():
    """Test listing messages."""
    print("=" * 60)
    print("📧 TEST: List Messages (Resource)")
    print("=" * 60)
    
    messages = client.list_messages(max_results=10)
    print(f"Found {len(messages)} messages")
    
    if messages:
        print("\nFirst 5 messages:")
        for i, msg in enumerate(messages[:5], 1):
            print(f"{i}. {msg.get('subject', 'No subject')}")
            print(f"   From: {msg.get('from', 'Unknown')}")
            print(f"   Date: {msg.get('date', 'Unknown')}")
            print(f"   Snippet: {msg.get('snippet', '')[:100]}...")
            print()
    else:
        print("No messages found.")
    
    return messages


def test_get_message(message_id: str):
    """Test getting a specific message."""
    print("=" * 60)
    print(f"🔍 TEST: Get Message Details (Resource) - {message_id[:20]}...")
    print("=" * 60)
    
    message = client.get_message(message_id)
    
    if message:
        print(f"Subject: {message.get('subject', 'No subject')}")
        print(f"From: {message.get('from', 'Unknown')}")
        print(f"To: {message.get('to', 'Unknown')}")
        print(f"Date: {message.get('date', 'Unknown')}")
        print(f"\nBody preview (first 200 chars):")
        body = message.get('body', '')
        print(body[:200] + "..." if len(body) > 200 else body)
        return message
    else:
        print("❌ Message not found")
        return None


def test_send_email(to_email: str = None):
    """Test sending an email."""
    print("=" * 60)
    print("✉️  TEST: Send Email")
    print("=" * 60)
    
    # Use a test email or prompt for one
    if not to_email:
        # Default to sending to yourself (you can change this)
        to_email = input("Enter recipient email (or press Enter to skip): ").strip()
        if not to_email:
            print("⏭️  Skipping send email test")
            return None
    
    subject = f"MCP Test Email - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    body = f"""This is a test email sent via Gmail MCP tools.

Sent at: {datetime.now().isoformat()}

This email was automatically generated by the Gmail MCP test script.
If you received this, the send_email tool is working correctly!

Best regards,
Gmail MCP Test Script
"""
    
    print(f"Sending email to: {to_email}")
    print(f"Subject: {subject}")
    
    result = client.send_message(
        to=to_email,
        subject=subject,
        body=body,
        body_type="text/plain"
    )
    
    if result:
        print(f"✅ Email sent successfully!")
        print(f"   Message ID: {result.get('id')}")
        print(f"   Thread ID: {result.get('threadId')}")
        return result
    else:
        print("❌ Failed to send email")
        return None


def test_list_messages_with_query():
    """Test listing messages with a search query."""
    print("=" * 60)
    print("🔍 TEST: List Messages with Query (Resource)")
    print("=" * 60)
    
    # Search for messages from today
    query = f"after:{datetime.now().strftime('%Y/%m/%d')}"
    print(f"Query: {query}")
    
    messages = client.list_messages(query=query, max_results=5)
    print(f"Found {len(messages)} messages matching query")
    
    if messages:
        print("\nMatching messages:")
        for i, msg in enumerate(messages, 1):
            print(f"{i}. {msg.get('subject', 'No subject')}")
            print(f"   From: {msg.get('from', 'Unknown')}")
            print(f"   Date: {msg.get('date', 'Unknown')}")
            print()
    
    return messages


def test_list_unread_messages():
    """Test listing unread messages."""
    print("=" * 60)
    print("📬 TEST: List Unread Messages (Resource)")
    print("=" * 60)
    
    messages = client.list_messages(
        query="is:unread",
        max_results=5,
        label_ids=["UNREAD"]
    )
    print(f"Found {len(messages)} unread messages")
    
    if messages:
        print("\nUnread messages:")
        for i, msg in enumerate(messages, 1):
            print(f"{i}. {msg.get('subject', 'No subject')}")
            print(f"   From: {msg.get('from', 'Unknown')}")
            print(f"   Date: {msg.get('date', 'Unknown')}")
            print()
    
    return messages


def main():
    """Run all tests in sequence."""
    print("=" * 60)
    print("🚀 GMAIL MCP TOOLS - TEST FLOW")
    print("=" * 60)
    
    # STEP 1: List messages
    print("\nSTEP 1: Listing messages...")
    messages = test_list_messages()
    
    # STEP 2: Get a specific message (if available)
    if messages:
        print("\nSTEP 2: Getting message details...")
        first_message_id = messages[0].get('id')
        if first_message_id:
            test_get_message(first_message_id)
    else:
        print("\nSTEP 2: Skipping (no messages to retrieve)")
    
    # STEP 3: List unread messages
    print("\nSTEP 3: Listing unread messages...")
    test_list_unread_messages()
    
    # STEP 4: List messages with query
    print("\nSTEP 4: Listing messages with query...")
    test_list_messages_with_query()
    
    # STEP 5: Send a test email (optional)
    print("\nSTEP 5: Sending test email...")
    sent_result = test_send_email()
    
    # STEP 6: List messages again to see if sent email appears
    if sent_result:
        print("\nSTEP 6: Listing messages again (to verify sent email)...")
        # Wait a moment for Gmail to process
        import time
        print("   Waiting 2 seconds for Gmail to process...")
        time.sleep(2)
        
        # Search for the email we just sent
        query = f"subject:\"MCP Test Email\""
        sent_messages = client.list_messages(query=query, max_results=5)
        if sent_messages:
            print(f"✅ Found {len(sent_messages)} sent test email(s)")
        else:
            print("⚠️  Sent email not yet visible (may take a few seconds)")
    
    print("\n" + "=" * 60)
    print("✅ TEST FLOW COMPLETED!")
    print("=" * 60)
    print("📧 Gmail MCP tools are working correctly!")
    print("   You can check your Gmail inbox to verify the sent email.")


if __name__ == "__main__":
    main()
