"""
Test script for Google Drive MCP tools and resources.

Tests Drive operations in a sequential flow:
1. List root folder (resource)
2. Create a test folder (tool)
3. Create a test file (tool)
4. Get file info (resource)
5. Get file content (resource)
6. Update file (tool)
7. Rename file (tool)
8. Move file (tool)
9. List folder again (resource)
10. Search files (resource)
"""
import sys
from pathlib import Path
from typing import Optional

# Add project root to path
# test_script.py is in: covalent_mcp/toolclasses/google/drive/
# Need to go up 5 levels to get to project root
covalent_mcp_dir = Path(__file__).parent.parent.parent.parent  # Gets to covalent_mcp/
project_root = covalent_mcp_dir.parent  # Gets to project root
sys.path.insert(0, str(project_root))

from covalent_mcp.toolclasses.google.gauth import GoogleAuth, DEFAULT_SCOPES
from covalent_mcp.toolclasses.google.drive.drive_client import DriveService


# Initialize client (shared across all tests)
auth = GoogleAuth(scopes=DEFAULT_SCOPES)
client = DriveService(auth=auth)

# Test folder and file names
TEST_FOLDER_NAME = "MCP Test Folder"
TEST_FILE_NAME = "mcp_test_file.txt"


def test_list_root_folder():
    """Test listing root folder."""
    print("=" * 60)
    print("📂 TEST: List Root Folder (Resource)")
    print("=" * 60)
    
    result = client.list_folder(folder_id=None, max_results=10)
    files = result.get("files", [])
    
    print(f"Found {len(files)} items in root folder\n")
    
    if files:
        print("First 5 items:")
        for i, item in enumerate(files[:5], 1):
            is_folder = item.get("mimeType") == "application/vnd.google-apps.folder"
            icon = "📁" if is_folder else "📄"
            print(f"{i}. {icon} {item.get('name', 'Unknown')}")
            print(f"   ID: {item.get('id')}")
            print(f"   Type: {item.get('mimeType', 'Unknown')}")
            print()
    else:
        print("Root folder is empty.")
    
    return files


def test_create_folder():
    """Test creating a folder."""
    print("=" * 60)
    print(f"➕ TEST: Create Folder - {TEST_FOLDER_NAME}")
    print("=" * 60)
    
    # Check if folder already exists
    search_result = client.search_files(
        query=f"name = '{TEST_FOLDER_NAME}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false",
        max_results=1
    )
    
    if search_result.get("files"):
        existing_folder = search_result["files"][0]
        print(f"Folder '{TEST_FOLDER_NAME}' already exists. Reusing.")
        print(f"   ID: {existing_folder.get('id')}")
        return existing_folder
    
    folder = client.create_folder(name=TEST_FOLDER_NAME)
    
    if folder:
        print(f"✅ Created folder: {folder.get('name')}")
        print(f"   ID: {folder.get('id')}")
        print(f"   Link: {folder.get('webViewLink')}")
        return folder
    else:
        print("❌ Failed to create folder")
        return None


def test_create_text_file(folder_id: Optional[str] = None):
    """Test creating a text file."""
    print("=" * 60)
    print(f"➕ TEST: Create Text File - {TEST_FILE_NAME}")
    print("=" * 60)
    
    content = """This is a test file created via Google Drive MCP tools.

Created at: 2026-01-22

This file was automatically generated by the Drive MCP test script.
If you can see this content, the create_text_file tool is working correctly!

You can update this file using the update_text_file tool.
"""
    
    file = client.create_text_file(
        name=TEST_FILE_NAME,
        content=content,
        parent_folder_id=folder_id
    )
    
    if file:
        print(f"✅ Created file: {file.get('name')}")
        print(f"   ID: {file.get('id')}")
        print(f"   Link: {file.get('webViewLink')}")
        return file
    else:
        print("❌ Failed to create file")
        return None


def test_get_file(file_id: str):
    """Test getting file information."""
    print("=" * 60)
    print(f"🔍 TEST: Get File Info (Resource) - {file_id[:20]}...")
    print("=" * 60)
    
    file = client.get_file(file_id)
    
    if file:
        print(f"Name: {file.get('name')}")
        print(f"ID: {file.get('id')}")
        print(f"Type: {file.get('mimeType')}")
        print(f"Modified: {file.get('modifiedTime')}")
        if file.get('size'):
            print(f"Size: {file.get('size')} bytes")
        if file.get('webViewLink'):
            print(f"Link: {file.get('webViewLink')}")
        return file
    else:
        print("❌ File not found")
        return None


def test_get_file_content(file_id: str):
    """Test getting file content."""
    print("=" * 60)
    print(f"📄 TEST: Get File Content (Resource) - {file_id[:20]}...")
    print("=" * 60)
    
    content = client.get_file_content(file_id)
    
    if content:
        print(f"Content preview (first 200 chars):")
        print(content[:200] + "..." if len(content) > 200 else content)
        print(f"\nTotal length: {len(content)} characters")
        return content
    else:
        print("❌ Failed to get file content")
        return None


def test_update_text_file(file_id: str):
    """Test updating a text file."""
    print("=" * 60)
    print(f"✏️  TEST: Update Text File - {file_id[:20]}...")
    print("=" * 60)
    
    updated_content = """This is an UPDATED test file created via Google Drive MCP tools.

Updated at: 2026-01-22

This file was automatically updated by the Drive MCP test script.
The update_text_file tool is working correctly!

You can see that the content has been changed.
"""
    
    file = client.update_text_file(
        file_id=file_id,
        content=updated_content
    )
    
    if file:
        print(f"✅ Updated file: {file.get('name')}")
        print(f"   Modified: {file.get('modifiedTime')}")
        return file
    else:
        print("❌ Failed to update file")
        return None


def test_rename_file(file_id: str):
    """Test renaming a file."""
    print("=" * 60)
    print(f"🏷️  TEST: Rename File - {file_id[:20]}...")
    print("=" * 60)
    
    new_name = "mcp_test_file_renamed.txt"
    file = client.rename_file(file_id, new_name)
    
    if file:
        print(f"✅ Renamed file to: {file.get('name')}")
        return file
    else:
        print("❌ Failed to rename file")
        return None


def test_move_file(file_id: str, destination_folder_id: str):
    """Test moving a file."""
    print("=" * 60)
    print(f"📦 TEST: Move File - {file_id[:20]}...")
    print("=" * 60)
    
    file = client.move_file(file_id, destination_folder_id)
    
    if file:
        print(f"✅ Moved file: {file.get('name')}")
        print(f"   New parent: {file.get('parents', [])}")
        return file
    else:
        print("❌ Failed to move file")
        return None


def test_search_files(query: str):
    """Test searching for files."""
    print("=" * 60)
    print(f"🔍 TEST: Search Files (Resource) - '{query}'")
    print("=" * 60)
    
    result = client.search_files(query=query, max_results=10)
    files = result.get("files", [])
    
    print(f"Found {len(files)} files matching query\n")
    
    if files:
        print("Matching files:")
        for i, file in enumerate(files, 1):
            print(f"{i}. {file.get('name')}")
            print(f"   ID: {file.get('id')}")
            print(f"   Type: {file.get('mimeType')}")
            print()
    
    return files


def main():
    """Run all tests in sequence."""
    print("=" * 60)
    print("🚀 GOOGLE DRIVE MCP TOOLS - TEST FLOW")
    print("=" * 60)
    
    # STEP 1: List root folder
    print("\nSTEP 1: Listing root folder...")
    root_files = test_list_root_folder()
    
    # STEP 2: Create test folder
    print("\nSTEP 2: Creating test folder...")
    test_folder = test_create_folder()
    test_folder_id = test_folder.get("id") if test_folder else None
    
    # STEP 3: Create test file in root
    print("\nSTEP 3: Creating test file in root...")
    test_file = test_create_text_file()
    test_file_id = test_file.get("id") if test_file else None
    
    if not test_file_id:
        print("\n⚠️  Cannot continue without test file. Exiting.")
        return
    
    # STEP 4: Get file info
    print("\nSTEP 4: Getting file information...")
    test_get_file(test_file_id)
    
    # STEP 5: Get file content
    print("\nSTEP 5: Getting file content...")
    test_get_file_content(test_file_id)
    
    # STEP 6: Update file
    print("\nSTEP 6: Updating file...")
    test_update_text_file(test_file_id)
    
    # STEP 7: Rename file
    print("\nSTEP 7: Renaming file...")
    renamed_file = test_rename_file(test_file_id)
    if renamed_file:
        test_file_id = renamed_file.get("id")  # Update ID in case it changed
    
    # STEP 8: Move file to test folder (if folder was created)
    if test_folder_id:
        print("\nSTEP 8: Moving file to test folder...")
        test_move_file(test_file_id, test_folder_id)
    
    # STEP 9: List test folder
    if test_folder_id:
        print("\nSTEP 9: Listing test folder...")
        folder_files = client.list_folder(folder_id=test_folder_id, max_results=10)
        print(f"Found {len(folder_files.get('files', []))} items in test folder")
        for item in folder_files.get("files", []):
            print(f"  - {item.get('name')}")
    
    # STEP 10: Search for test files
    print("\nSTEP 10: Searching for test files...")
    test_search_files(f"name contains 'mcp_test'")
    
    print("\n" + "=" * 60)
    print("✅ TEST FLOW COMPLETED!")
    print("=" * 60)
    print("📁 Google Drive MCP tools are working correctly!")
    if test_folder:
        print(f"   Test folder: {test_folder.get('webViewLink')}")
    if test_file:
        print(f"   Test file: {test_file.get('webViewLink')}")


if __name__ == "__main__":
    main()
