use reqwest;
use serde::{Deserialize, Serialize};
use anyhow::{Result, Context as AnyhowContext};
use crate::screen_context::ContextAnalysisOutput;

const FLASK_API_URL: &str = "http://127.0.0.1:5001";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextPayload {
    pub description: String,
    pub data: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionItem {
    pub action_uuid: String,
    pub action_name: String,
    pub action_plan: String,
    pub action_prompt: String,
    pub last_selected: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextResponse {
    pub message: String,
    pub action_name: Option<String>,
    pub action_plan: Option<String>,
    pub action_prompt: Option<String>,
    pub action_uuid: Option<String>,
    pub recent_actions: Option<Vec<ActionItem>>,
}

/// HTTP client for sending context data to Flask API
pub struct ContextApiClient {
    client: reqwest::Client,
    base_url: String,
}

impl ContextApiClient {
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(120))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url: FLASK_API_URL.to_string(),
        }
    }

    pub fn with_base_url(base_url: String) -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(120))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url,
        }
    }

    /// Check if the Flask server is healthy
    pub async fn health_check(&self) -> Result<bool> {
        let url = format!("{}/health", self.base_url);
        
        match self.client.get(&url).send().await {
            Ok(response) => Ok(response.status().is_success()),
            Err(_) => Ok(false),
        }
    }

    /// Send context data to the Flask API
    pub async fn send_context(&self, description: String, data: String) -> Result<ContextResponse> {
        let url = format!("{}/screen", self.base_url);
        
        let payload = ContextPayload { description, data };
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send request to Flask API")?;

        if response.status().is_success() {
            let context_response: ContextResponse = response
                .json()
                .await
                .context("Failed to parse response from Flask API")?;
            
            Ok(context_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Send analysis output to Flask API
    pub async fn send_analysis_output(&self, analysis: &ContextAnalysisOutput) -> Result<ContextResponse> {
        // Use the description from ContextAnalysisOutput (generated by Claude)
        let description = analysis.description.clone();
        
        // Serialize the entire analysis output as data
        let data = serde_json::to_string(analysis)
            .context("Failed to serialize analysis output")?;
        
        self.send_context(description, data).await
    }

    /// Trigger an action by UUID via Flask API
    pub async fn trigger_action(&self, action_uuid: String, action_prompt: String) -> Result<serde_json::Value> {
        let url = format!("{}/trigger_action", self.base_url);
        
        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "action": action_prompt
        });
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send trigger_action request to Flask API")?;

        if response.status().is_success() {
            let json_response: serde_json::Value = response
                .json()
                .await
                .context("Failed to parse trigger_action response from Flask API")?;
            
            Ok(json_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API trigger_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Edit an action via Flask API (optionally persist)
    pub async fn edit_action(
        &self,
        action_uuid: String,
        action_name: String,
        action_plan: String,
        action_prompt: String,
        persist: bool
    ) -> Result<serde_json::Value> {
        let url = format!("{}/edit_action", self.base_url);

        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "action_override": {
                "action_name": action_name,
                "action_plan": action_plan,
                "action_prompt": action_prompt
            },
            "persist": persist
        });

        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send edit_action request to Flask API")?;

        if response.status().is_success() {
            let json_response: serde_json::Value = response
                .json()
                .await
                .context("Failed to parse edit_action response from Flask API")?;

            Ok(json_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API edit_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Trigger an action by UUID with optional override via Flask API
    pub async fn trigger_action_with_override(
        &self,
        action_uuid: String,
        action_name: String,
        action_plan: String,
        action_prompt: String
    ) -> Result<serde_json::Value> {
        let url = format!("{}/trigger_action", self.base_url);

        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "action_override": {
                "action_name": action_name,
                "action_plan": action_plan,
                "action_prompt": action_prompt
            }
        });

        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send trigger_action request to Flask API")?;

        if response.status().is_success() {
            let json_response: serde_json::Value = response
                .json()
                .await
                .context("Failed to parse trigger_action response from Flask API")?;

            Ok(json_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API trigger_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }
}

impl Default for ContextApiClient {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_health_check() {
        let client = ContextApiClient::new();
        // This will fail if Flask server is not running, which is expected in tests
        let _result = client.health_check().await;
    }

}
