use reqwest;
use serde::{Deserialize, Serialize};
use anyhow::{Result, Context as AnyhowContext};
use crate::screen_context::ContextAnalysisOutput;

fn flask_api_url() -> String {
    let port = std::env::var("VITE_FLASK_PORT").unwrap_or_else(|_| "15001".to_string());
    format!("http://127.0.0.1:{}", port)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextPayload {
    pub description: String,
    pub data: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionItem {
    pub action_uuid: String,
    pub action_name: String,
    pub action_plan: String,
    pub last_selected: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextResponse {
    pub message: String,
    pub action_name: Option<String>,
    pub action_plan: Option<String>,
    pub action_uuid: Option<String>,
    pub recent_actions: Option<Vec<ActionItem>>,
}

/// HTTP client for sending context data to Flask API
pub struct ContextApiClient {
    client: reqwest::Client,
    base_url: String,
}

impl ContextApiClient {
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(120))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url: flask_api_url(),
        }
    }

    pub fn with_base_url(base_url: String) -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(120))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url,
        }
    }

    /// Check if the Flask server is healthy
    pub async fn health_check(&self) -> Result<bool> {
        let url = format!("{}/health", self.base_url);
        
        match self.client.get(&url).send().await {
            Ok(response) => Ok(response.status().is_success()),
            Err(_) => Ok(false),
        }
    }

    /// Send context data to the Flask API
    pub async fn send_context(&self, description: String, data: String) -> Result<ContextResponse> {
        let url = format!("{}/screen", self.base_url);
        
        let payload = ContextPayload { description, data };
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send request to Flask API")?;

        if response.status().is_success() {
            let context_response: ContextResponse = response
                .json()
                .await
                .context("Failed to parse response from Flask API")?;
            
            Ok(context_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Send analysis output to Flask API
    pub async fn send_analysis_output(&self, analysis: &ContextAnalysisOutput) -> Result<ContextResponse> {
        // Use the description from ContextAnalysisOutput (generated by Claude)
        let description = analysis.description.clone();
        
        // Serialize the entire analysis output as data
        let data = serde_json::to_string(analysis)
            .context("Failed to serialize analysis output")?;
        
        self.send_context(description, data).await
    }

    /// Plan an action by UUID via Flask API (new flow - Phase 1)
    /// Returns the action plan for user approval/editing before execution
    pub async fn plan_action(&self, action_uuid: String, action_override: Option<serde_json::Value>) -> Result<serde_json::Value> {
        let url = format!("{}/plan_action", self.base_url);
        
        let mut payload = serde_json::json!({
            "action_uuid": action_uuid
        });
        
        if let Some(override_val) = action_override {
            payload["action_override"] = override_val;
        }
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send plan_action request to Flask API")?;

        // Accept 200 (success), 400 (bad request), and 500 (planning/MCP error) as
        // structured responses — Flask always returns {status, error} JSON for errors
        // so the frontend can surface the message cleanly.
        let status = response.status();
        if status.is_success() || status.as_u16() == 400 || status.as_u16() == 500 {
            let body = response.text().await.unwrap_or_default();
            let json_response: serde_json::Value = serde_json::from_str(&body)
                .context("Failed to parse plan_action response from Flask API")?;
            Ok(json_response)
        } else {
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API plan_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Execute an approved action via Flask API (new flow - Phase 2)
    /// Called after user approves/edits the action plan from plan_action
    pub async fn execute_action(&self, action_uuid: String, tool_name: String, parameters: serde_json::Value) -> Result<serde_json::Value> {
        let url = format!("{}/execute_action", self.base_url);
        
        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "tool_name": tool_name,
            "parameters": parameters
        });
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send execute_action request to Flask API")?;

        // Accept 200 (success) and 500 (tool error) as structured responses — Flask
        // returns {status, error} JSON even on 500 so the caller can surface the message.
        let status = response.status();
        if status.is_success() || status.as_u16() == 500 {
            let body = response.text().await.unwrap_or_default();
            let json_response: serde_json::Value = serde_json::from_str(&body)
                .context("Failed to parse execute_action response from Flask API")?;
            Ok(json_response)
        } else {
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API execute_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Execute multiple actions as a chain via Flask API
    /// Called for multi-action execution
    pub async fn execute_action_chain(&self, action_uuid: String, actions: Vec<serde_json::Value>) -> Result<serde_json::Value> {
        let url = format!("{}/execute_action", self.base_url);
        
        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "actions": actions
        });
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send execute_action_chain request to Flask API")?;

        // Accept 200 (all succeeded), 207 (partial), and 500 (all failed) as structured
        // responses — the JSON body always contains {status, results, summary} in all
        // three cases. Only treat non-parseable / unexpected failures as hard errors.
        let status = response.status();
        if status.is_success() || status.as_u16() == 207 || status.as_u16() == 500 {
            let body = response.text().await.unwrap_or_default();
            let json_response: serde_json::Value = serde_json::from_str(&body)
                .context("Failed to parse execute_action_chain response from Flask API")?;
            Ok(json_response)
        } else {
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API execute_action_chain returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Edit an action via Flask API (optionally persist)
    pub async fn edit_action(
        &self,
        action_uuid: String,
        action_name: String,
        action_plan: String,
        persist: bool
    ) -> Result<serde_json::Value> {
        let url = format!("{}/edit_action", self.base_url);

        let payload = serde_json::json!({
            "action_uuid": action_uuid,
            "action_override": {
                "action_name": action_name,
                "action_plan": action_plan
            },
            "persist": persist
        });

        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send edit_action request to Flask API")?;

        if response.status().is_success() {
            let json_response: serde_json::Value = response
                .json()
                .await
                .context("Failed to parse edit_action response from Flask API")?;

            Ok(json_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API edit_action returned error status {}: {}",
                status,
                error_text
            ))
        }
    }
}

impl Default for ContextApiClient {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_health_check() {
        let client = ContextApiClient::new();
        // This will fail if Flask server is not running, which is expected in tests
        let _result = client.health_check().await;
    }

}
