use reqwest;
use serde::{Deserialize, Serialize};
use anyhow::{Result, Context as AnyhowContext};
use crate::screen_context::ContextAnalysisOutput;

const FLASK_API_URL: &str = "http://127.0.0.1:5001";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextPayload {
    pub description: String,
    pub data: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextResponse {
    pub message: String,
    pub written: String,
}

/// HTTP client for sending context data to Flask API
pub struct ContextApiClient {
    client: reqwest::Client,
    base_url: String,
}

impl ContextApiClient {
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url: FLASK_API_URL.to_string(),
        }
    }

    pub fn with_base_url(base_url: String) -> Self {
        Self {
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
            base_url,
        }
    }

    /// Check if the Flask server is healthy
    pub async fn health_check(&self) -> Result<bool> {
        let url = format!("{}/health", self.base_url);
        
        match self.client.get(&url).send().await {
            Ok(response) => Ok(response.status().is_success()),
            Err(_) => Ok(false),
        }
    }

    /// Send context data to the Flask API
    pub async fn send_context(&self, description: String, data: String) -> Result<ContextResponse> {
        let url = format!("{}/screen", self.base_url);
        
        let payload = ContextPayload { description, data };
        
        let response = self.client
            .post(&url)
            .json(&payload)
            .send()
            .await
            .context("Failed to send request to Flask API")?;

        if response.status().is_success() {
            let context_response: ContextResponse = response
                .json()
                .await
                .context("Failed to parse response from Flask API")?;
            
            Ok(context_response)
        } else {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            Err(anyhow::anyhow!(
                "Flask API returned error status {}: {}",
                status,
                error_text
            ))
        }
    }

    /// Send analysis output to Flask API
    pub async fn send_analysis_output(&self, analysis: &ContextAnalysisOutput) -> Result<ContextResponse> {
        // Use the description from ContextAnalysisOutput (generated by Claude)
        let description = analysis.description.clone();
        
        // Serialize the entire analysis output as data
        let data = serde_json::to_string(analysis)
            .context("Failed to serialize analysis output")?;
        
        self.send_context(description, data).await
    }
}

impl Default for ContextApiClient {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_health_check() {
        let client = ContextApiClient::new();
        // This will fail if Flask server is not running, which is expected in tests
        let _result = client.health_check().await;
    }

}

